# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobs-parser
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pg_data:
