"""initial

Revision ID: 282fde13e6ed
Revises: 
Create Date: 2025-06-08 13:42:01.822310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282fde13e6ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('company', sa.String(), nullable=True),
                    sa.Column('company_url', sa.String(), nullable=True),
                    sa.Column('apply_url', sa.String(), nullable=True),
                    sa.Column('salary', sa.String(), nullable=True),
                    sa.Column('parsed_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('jobprocessingstatus',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('job_id', sa.Uuid(), nullable=False),
                    sa.Column('status', sa.Enum('APPLIED', 'NOT_SUITABLE',
                                                name='jobprocessingstatusenum'), nullable=False),
                    sa.Column('comment', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('job_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobprocessingstatus')
    op.drop_table('job')
    # ### end Alembic commands ###
