"""add amocrm fields to job

Revision ID: 77d30efe11ae
Revises: e62018ba8390
Create Date: 2025-12-28 20:20:41.802112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77d30efe11ae'
down_revision: Union[str, None] = 'e62018ba8390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('amocrm_lead_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job', sa.Column('amocrm_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'amocrm_created_at')
    op.drop_column('job', 'amocrm_lead_id')
    # ### end Alembic commands ###
