"""add user_id to job_processing_status

Revision ID: 929dcc4a6398
Revises: f2b3ca71770f
Create Date: 2025-06-14 18:06:17.740030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929dcc4a6398'
down_revision: Union[str, None] = 'f2b3ca71770f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем только записи без user_id
    # op.execute('DELETE FROM jobprocessingstatus WHERE user_id IS NULL')

    # Добавляем новое поле
    op.add_column('jobprocessingstatus', sa.Column(
        'user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'jobprocessingstatus',
                          'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobprocessingstatus', type_='foreignkey')
    op.drop_column('jobprocessingstatus', 'user_id')
    # ### end Alembic commands ###
